# Generated by Django 5.1.6 on 2025-02-28 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='documents',
            field=models.ManyToManyField(related_name='categories', to='document.document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='document_do_user_id_57c4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='document_ca_name_c3a75d_idx'),
        ),
    ]
