# Generated by Django 5.1.6 on 2025-03-05 15:01

import document.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='json_content',
        ),
        migrations.AddField(
            model_name='document',
            name='formatted_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[document.validators.validate_file_extension, document.validators.validate_file_size]),
        ),
    ]
