# Generated by Django 5.1.6 on 2025-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_rename_content_document_json_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('PDFToImagesService', 'PDF To Images'), ('ImageToTextService', 'Extract Text From Image'), ('IdentifyCategoryService', 'Identify Category'), ('FormatContentService', 'Format Content'), ('SummaryFromContentService', 'Summarize Content'), ('ContentToJSONService', 'Convert Content to JSON')], max_length=50, unique=True)),
                ('implementation', models.CharField(help_text="Enter the full module path, e.g., 'document.utils.PDFToImagesService.PDFToImageUsingPDF2ImagePackage'", max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
    ]
